# Generated by Django 4.2.17 on 2024-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedition',
            old_name='stock_count',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
